services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes: 
      - /home/ahmet/data/mariadb:/var/lib/mysql
      - ../secrets/db_credentials.txt:/run/secrets/db_credentials.txt:ro
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    volumes: 
      - /home/ahmet/data/wordpress:/var/www/wordpress
      - ../secrets/wp_credentials.txt:/run/secrets/wp_credentials.txt:ro
      - ../secrets/db_credentials.txt:/run/secrets/db_credentials.txt:ro
    networks:
      - inception
    depends_on:
      - mariadb
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    env_file: .env
    ports:
      - "443:443"
    volumes: 
      - /home/ahmet/data/wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress

networks:
  inception:
